INSERT INTO EXCHANGE_VALUE (ID, CURRENCY_FROM,CURRENCY_TO, CONVERSION_MULTIPLE,PORT)
VALUES(100L, 'USD','INR',71,0);

INSERT INTO EXCHANGE_VALUE (ID, CURRENCY_FROM,CURRENCY_TO, CONVERSION_MULTIPLE,PORT)
VALUES(101L, 'EUR','INR',78.8,0);
INSERT INTO EXCHANGE_VALUE (ID, CURRENCY_FROM,CURRENCY_TO, CONVERSION_MULTIPLE,PORT)
VALUES(102L, 'AUD','INR',48.8,0);